name: Generate Report
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone
        run: git clone https://github.com/shopware/platform.git

      - name: Run Qodana
        run: |
          mkdir out
          docker run --rm -it -v $(pwd)/platform/:/data/project/ -v $(pwd)/out/:/data/results/ jetbrains/qodana-php
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
