name: Generate Report
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        run: git clone https://github.com/shopware/platform.git
        
      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer:v2
          
      - name: Install Composer
        run: composer install --no-scripts -n
        
      - name: Setup Deploy key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
          
      - name: Setup known hosts
        run: ssh-keyscan -H qodana.fos.gg > ~/.ssh/known_hosts

      - name: Run Qodana
        run: |
          mkdir out
          docker run --rm -v $(pwd)/platform/:/data/project/ -v $(pwd)/out/:/data/results/ jetbrains/qodana-php
          rm out/log/idea*.log
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
